name: testedenis
favicon: null
layout_spectrum: 0.7386210984550416
typography_spectrum: 0.12324552843347192
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171111'
    - '#ffffff'
    - '#726763'
    - '#c7c3b8'
    - '#9e968b'
  brandStrength: 0.1875
  lightness: 0.7817755935247988
  saturation: 0.26782184187322855
  rhythmicContrast: 0.047818530816584826
purpose: []
