name: testedenis
favicon: null
layout_spectrum: 0.7386210984550416
typography_spectrum: 0.12324552843347192
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#222328'
    - '#bdc6c5'
    - '#7d7159'
    - '#fe9e74'
  brandStrength: 0.3125
  lightness: 0.7817755935247988
  saturation: 0.26782184187322855
  rhythmicContrast: 0.047818530816584826
purpose: []
